# Generated by Django 4.0.4 on 2022-05-06 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('L1_work_with_user_app', '0001_initial'),
        ('L3_serializers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, to='L1_work_with_user_app.myuser'),
        ),
    ]
