# Generated by Django 4.0.4 on 2022-05-16 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('L3_serializers', '0003_alter_project_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
