version: '3.1'  # version of docker-compose.yml file

services:
  db:
    image: postgres:13.1
    privileged: true
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: geekbrains
      POSTGRES_DB: todonotes
  backend:
    build:
      context: .
    expose:
      - 8080
    command: bash -c "
      ./wait-for-postgres.sh db
      && python manage.py migrate
      && python manage.py fill_db
      && python manage.py fill_prj_todo
      && gunicorn todonotes.wsgi -b 0.0.0.0:8080"
    depends_on:
      - db
  nginx:
    build: ./nginx
    ports:
      - 8000:80
    depends_on:
      - backend
      